### ISSUE TITLE
rMSI2::ProcessImages() - checksum warning

### ISSUE THREAD

**Issue by goterm** [prafols/rMSI2#1]
Hi,

when I run:
rMSI2::ProcessImages(proc_params, data_desc) 

the processing starts and ends without errors but I get a **warning**:

Parsingng ROI info of imzML 1 of 1
Loading image 1 of 1
Parsing XML data in imzML file...
Checking ibd UUID...OK
**WARNING: Checksum validation is disabled, data may be corrupt!**
Calculating the new mass axis...
....
is this something to worry about? Can I enable/control the validation?

thanks!

**Comment by prafols** [comment]
Hi,

nothing to worry about. The checksum verification is disabled by default because it may take a very long time for large datasets.  Moreover, some imzML files obtained from some vendors do not have a properly calculated checksum and will throw a false error after a long wait.

The checksum validation is implemented in rMSI2. You can force it to be calculated using the verifyImzMLChecksums = T argument to the ProcessImages() function.

Best
